---
- name: Apache server installed
  hosts: localhost

  tasks:
  - name: Network resources {{ 'Create' if network_tf_state == 'present' else 'Delete' }}
    environment:
      TF_BACKEND_BUCKET: "{{ cluster_name }}-terraform"
      TF_VAR_aws_region: "{{ aws_region }}"
      TF_VAR_aws_access_key_id: "{{ TF_VAR_aws_access_key_id }}"
      TF_VAR_aws_secret_access_key: "{{ aws_secret_access_key }}"
      TF_VAR_ssh_pubkey: "{{ ssh_pubkey }}"
      TF_VAR_pull_secret: "{{ pull_secret }}"
      TF_VAR_base_domain: "{{ base_domain }}"
      TF_VAR_infra_name: "{{ infra_name }}"
      TF_VAR_vpc_cidr: "{{ vpc_cidr }}"
    cloud.terraform.terraform:
      project_path: "{{ work_dir }}/{{ cluster_name }}/{{ role_name }}/"
      force_init: true
      provider_upgrade: true
      state: "{{ network_tf_state }}"
    register: network_output
